DELIMITER $$

CREATE PROCEDURE albuns_do_artista(IN SINGER_NAME VARCHAR(100))
BEGIN
SELECT S.SINGER AS `artista`,
A.ALBUM AS `album`
FROM SINGERS AS S
INNER JOIN ALBUMS AS A ON A.SINGER_ID = S.SINGER_ID
WHERE SINGER_NAME = S.SINGER
ORDER BY `album`;
END $$

DELIMITER $$;
