DELIMITER $$

CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON USERS
FOR EACH ROW
BEGIN
DELETE FROM FOLLOW
WHERE USER_ID = OLD.USER_ID;
DELETE FROM SONG_HISTORY
WHERE USER_ID = OLD.USER_ID;
END $$

DELIMITER $$;
